# Helps catch spelling errors
name: Codespell

on:
  pull_request:

permissions: {}

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
        with:
          skip: .git,_artifacts,*.sum,.golangci.yml
          ignore_words_file: .codespellignore
          check_filenames: true
          check_hidden: true
