# Check for broken links
name: Link-check

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  pull_request:
    paths: "docs/**"

permissions: {}

jobs:
  lint_docs:
    name: Broken Links
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # v1.0.15
      with:
        use-quiet-mode: 'yes'
        config-file: ".markdownlinkcheck.json"
